# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Zygmunt's Blog
description:      A bit about AI, a bit about musicals
baseurl:          /

author:
  name:           'Zygmunt'

paginate:         5


plugins: [jekyll-paginate]